### ISSUE TITLE
 Peer authentication failed for user "django"

### ISSUE THREAD

**Issue by ashishpahwa7** [rjvjha1996/Aceproject#1]
(rajeev) ash@ash-008:~/Desktop/ACE-Selections2016/RajeevJha/Aceproject-master/src$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(_args, *_options)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in **init**
    self.loader = MigrationLoader(self.connection)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in **init**
    self.build_graph()
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 233, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ash/Desktop/ACE-Selections2016/RajeevJha/rajeev/local/lib/python2.7/site-packages/psycopg2/**init**.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "django"

**Comment by rjvjha** [comment]
This error is arising due to change of database cridentials .I am trying to deploy this web application on VPS .That's why this app won't run in local systems.you can run  it by database settings to default sqlite3.
